# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  bash_execute:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Make script executable
        run: chmod +x ./basci.sh   # adjust path/name if it's actually basic.sh

      - name: Create folder, run script, create file
        run: |
          mkdir myfolder
          cp ./basci.sh myfolder/
          cd myfolder
          # Script is in repo root, so call it via ..
          bash ./basci.sh
          touch newfile

      - name: Upload artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: myfolder/newfile
          if-no-files-found: error
