
name: CI

on:
  push:
    branches: [ "master" ]     # change if your default branch is different
  pull_request:
    branches: [ "master" ]
  workflow_dispatch: 

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Setting up the environment"
