
name: CI

on:
  push:
    branches: [ "master" ]     # change if your default branch is different
  pull_request:
    branches: [ "master" ]
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "CI is running ✅"
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is a test job"
  delay:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - run: echo "This job is delayed"